project_name: tarragon
builds:
  - env: [CGO_ENABLED=0]
		ldflags:
			- -s -w -X main.version={{.Tag}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Simon Ho <simonho.ubc@gmail.com>
    description: Quick Terraform actions across multiple projects.
    homepage: https://github.com/sho-87/tarragon
    license: MIT
    formats:
      - deb
      - rpm
      - apk